---
- name: install required packages
  package:
    name: "{{ kea_required_packages }}"
    state: present

- name: ensure apt key is present
  ansible.builtin.apt_key:
    id: 63D408891D8B8D01
    keyring: "/usr/share/keyrings/isc-kea-2-6-archive-keyring.gpg"
    url: "https://dl.cloudsmith.io/public/isc/kea-2-6/gpg.63D408891D8B8D01.key"

- name: ensure apt repo is present
  apt_repository:
    state: present
    repo: "{{ item }}"
    update_cache: yes
    filename: isc-kea-2.6
  loop:
    - "deb [signed-by=/usr/share/keyrings/isc-kea-2-6-archive-keyring.gpg] https://dl.cloudsmith.io/public/isc/kea-2-6/deb/debian bookworm main"
    - "deb-src [signed-by=/usr/share/keyrings/isc-kea-2-6-archive-keyring.gpg] https://dl.cloudsmith.io/public/isc/kea-2-6/deb/debian bookworm main"

- name: install dhcp packages
  package:
    name: "isc-{{ item }}"
    state: latest
  loop: "{{ kea_packages }}"
  notify:
    - restart isc-kea-dhcp4-server

- name: configure kea dhcp server
  template:
    src: kea_dhcp4.conf.j2
    dest: /etc/kea/kea-dhcp4.conf
  notify: restart isc-kea-dhcp4-server

- name: install kea-exporter
  pip:
    name: kea-exporter
    state: latest
    executable: pip3
    break_system_packages: True
  notify: restart kea-exporter

- name: create systemd unit for exporter
  template:
    src: "kea-exporter.service.j2"
    dest: "/etc/systemd/system/kea-exporter.service"
  notify:
    - reload systemd
    - restart kea-exporter

- name: write vhost for exporter
  template:
    src: kea_exporter_vhost.conf.j2
    dest: /etc/nginx/conf.d/kea_exporter.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: enable systemd units
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - isc-kea-dhcp4-server
    - kea-exporter
