---
- name: ensure apt key is present
  apt_key:
    state: present
    id: ADA7268E
    url: "https://dl.cloudsmith.io/public/isc/kea-1-8/cfg/gpg/gpg.4DD5AE28ADA7268E.key"

- name: remove previous apt repo
  apt_repository:
    state: absent
    repo: "deb https://dl.cloudsmith.io/public/isc/kea-1-6/deb/debian {{ ansible_distribution_release }} main"
    filename: isc-kea

- name: ensure apt repo is present
  apt_repository:
    state: present
    repo: "deb https://dl.cloudsmith.io/public/isc/kea-1-8/deb/debian {{ ansible_distribution_release }} main"
    update_cache: yes
    filename: isc-kea

- name: remove old dhcp packages
  package:
    name: "{{ item }}"
    state: absent
  loop: "{{ kea_packages }}"

- name: install dhcp packages
  package:
    name: "isc-{{ item }}"
    state: latest
  loop: "{{ kea_packages }}"
  notify:
    - restart isc-kea-dhcp4-server

- name: create systemd override dir for kea-dhcp4-server.service
  file:
    path: /etc/systemd/system/isc-kea-dhcp4-server.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: configure systemd unit overrides
  template:
    src: kea_dhcp4_server_service_overrides.j2
    dest: /etc/systemd/system/isc-kea-dhcp4-server.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart isc-kea-dhcp4-server

- name: configure kea dhcp server
  template:
    src: kea_dhcp4.conf.j2
    dest: /etc/kea/kea-dhcp4.conf
  notify: restart isc-kea-dhcp4-server

- name: remove kea init file if present
  file:
    path: /etc/init.d/isc-kea-dhcp4-server
    state: absent
  notify: reload systemd

- name: install kea-exporter
  pip:
    name: kea-exporter
    state: latest
    executable: pip3
  notify: restart kea-exporter

- name: create systemd unit for exporter
  template:
    src: "kea-exporter.service.j2"
    dest: "/etc/systemd/system/kea-exporter.service"
  notify:
    - reload systemd
    - restart kea-exporter

- name: write vhost for exporter
  template:
    src: kea_exporter_vhost.conf.j2
    dest: /etc/nginx/conf.d/kea_exporter.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: enable systemd units
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - isc-kea-dhcp4-server
    - kea-exporter
