---
- name: install golang package
  apt:
    name: golang
    state: latest
    default_release: "{{ debian_repo }}"

- name: create GOPATH directory
  file:
    path: "{{ gopath }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: set GOPATH globally via profile.d
  template:
    src: go.sh.j2
    dest: /etc/profile.d/go.sh
    owner: root
    group: root
    mode: 0644

- name: build dep util
  shell: "go get -v -u github.com/golang/dep/cmd/dep"
  environment:
    GOPATH: "{{ gopath }}"
