# Install "gosu" utility.
#
# @see https://github.com/tianon/gosu
#

- name: set internal variables for convenience
  set_fact:
    gosu_bin_url: "https://github.com/tianon/gosu/releases/download/{{ gosu_version }}/gosu-amd64"

- name: download gosu executable
  get_url:
    url: "{{ gosu_bin_url }}"
    dest: "/usr/local/bin/gosu"

- name: add executable permission
  file:
    path: "/usr/local/bin/gosu"
    state: file
    mode: "a+x"
