---
- name: create anycast.netdev
  template:
    src: anycast.netdev.j2
    dest: "/etc/systemd/network/anycast.netdev"
  notify: restart networkd

- name: create anycast.network
  template:
    src: anycast.network.j2
    dest: "/etc/systemd/network/anycast.netdev"
  notify: restart networkd
