- src: geerlingguy.clamav
- src: geerlingguy.mysql
- src: geerlingguy.redis
- src: powerdns.pdns
- src: powerdns.pdns_recursor
- src: lean_delivery.java
- src: geerlingguy.php
- src: systemli.etherpad
- src: stackhpc.libvirt-host
- src: stackhpc.libvirt-vm
