---
dehydrated_dependencies:
  - git
  - openssl
  - curl
dehydrated_repo_url: https://github.com/lukas2511/dehydrated.git
dehydrated_install_root: /opt/dehydrated
dehydrated_update: yes
dehydrated_version: HEAD
dehydrated_key_algo: rsa
dehydrated_keysize: 4096
dehydrated_ca: "https://acme-v02.api.letsencrypt.org/directory"
dehydrated_cronjob: yes
dehydrated_run_on_changes: yes
dehydrated_systemd_timer: no
dehydrated_hook_scripts: []
dehydrated_cert_config: []
# dehydrated_systemd_timer_onfailure: some_unit.service
pdns_api_version: HEAD
pdns_api_repo_url: https://github.com/silkeh/pdns_api.sh.git
pdns_api_update: yes
