---
- name: run dehydrated
  command: "{{ dehydrated_install_root }}/dehydrated -c"
  when: dehydrated_run_on_changes

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Remove timer
  systemd:
    name: dehydrated.timer
    enabled: no
    state: stopped
