---
- name: write cpthook config
  template:
    src: "cpthook.yml.j2"
    dest: "{{ cpthook_config }}"
  notify: restart cpthook

- name: create systemd unit for cpthook
  template:
    src: "cpthook.service.j2"
    dest: "/etc/systemd/system/cpthook.service"
  notify: reload systemd

- name: download cpthook binary
  get_url:
    url: "{{ cpthook_url }}"
    dest:  "{{ cpthook_path }}"
    checksum: "sha256:{{ cpthook_url }}.sha256sum"
    mode: 0755
  notify: restart cpthook

- name: configure cpthook systemd unit
  systemd:
    name: "cpthook.service"
    enabled: yes
    state: started
