---
yanic_user: "yanic"
yanic_home: "/var/lib/yanic"
yanic_url: "https://bin.freifunk-mwu.de/yanic/yanic"
yanic_path: "/usr/local/bin/yanic"
yanic_database: "yanic"
yanic_config: "/etc/yanic.conf"
respondd_config: "/etc/respondd.conf"
