---
- name: Add rspamd + dovecot gpg key.
  apt_key:
    url: "{{ item }}"
    state: "present"
  loop:
    - "{{ apt_repo_gpg_dovecot }}"
    - "{{ apt_repo_gpg_rspamd }}"

- name: Add rspamd apt repository.
  apt_repository:
    repo: "{{ item }}"
    state: "present"
    filename: rspamd
  loop: "{{ apt_repo_url_rspamd }}"

- name: Add dovecot apt repository.
  apt_repository:
    repo: "{{ item }}"
    state: "present"
    filename: dovecot
  loop: "{{ apt_repo_url_dovecot }}"

- name: Update apt cache.
  apt:
    update_cache: "yes"

- name: Install mail packages.
  apt:
    name: "{{ _mail_packages }}"
    state: "present"

- import_tasks: clamav.yml
- import_tasks: redis.yml
- import_tasks: rspamd.yml
- import_tasks: modoboa.yml
- import_tasks: postfix.yml
- import_tasks: dovecot.yml
- import_tasks: mailman.yml
