---
- name: create system user
  user:
    name: "{{ yanic_user }}"
    home: "{{ yanic_home }}"
    shell: /bin/false

- name: download yanic
  get_url:
    url: "{{ yanic_url }}"
    dest:  "{{ yanic_path }}"
    checksum: "sha256:{{ yanic_url }}.sha256sum"
    mode: 0755
  notify:
    - reload systemd
    - restart respondd
    - restart yanic

- name: configure yanic
  include_tasks: yanic.yml
  when: server_type == "monitoring"

- name: configure respondd
  include_tasks: respondd.yml
