---
- name: ensure apt key for grafana is present
  apt_key:
    state: present
    id: 24098CB6
    url: "https://packages.grafana.com/gpg.key"

- name: ensure grafana apt repo is present
  apt_repository:
    state: present
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    update_cache: yes
    filename: grafana

- name: install grafana package
  package:
    name: grafana
    state: present

- name: copy grafana.ini
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    mode: 0640
  notify: restart grafana

- name: write vhost grafana.conf
  template:
    src: grafana_vhost.conf.j2
    dest: /etc/nginx/conf.d/grafana.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: install grafana-image-renderer dependencies
  package:
    name:
      - libx11-xcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxi6
      - libxtst6
      - libnss3
      - libcups2
      - libxss1
      - libxrandr2
      - libasound2
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libpangocairo-1.0-0
      - libgtk-3-0
    state: present

- name: install plugins
  grafana_plugin:
    name: "{{ item }}"
    version: latest
    state: present
  notify: restart grafana
  loop:
    - grafana-image-renderer

- name: enable systemd unit grafana
  systemd:
    name: grafana-server
    enabled: yes
    state: started

- name: add yanic datasource
  when: yanic_present is defined
  grafana_datasource:
    name: "yanic"
    grafana_url: "http://localhost:3000"
    grafana_user: "admin"
    grafana_password: "{{ lookup('passwordstore', 'grafana/admin') }}"
    ds_type: "influxdb"
    ds_url: "http://localhost:8086"
    database: "yanic"

- name: add prometheus datasource
  when: '"prometheus" in prometheus_components'
  grafana_datasource:
    name: "prometheus"
    grafana_url: "http://localhost:3000"
    grafana_user: "admin"
    grafana_password: "{{ lookup('passwordstore', 'grafana/admin') }}"
    ds_type: "prometheus"
    ds_url: "http://localhost:9090"
