---

- name: ensure correct ownership of /etc/fastd
  file: path=/etc/fastd state=directory mode=0750 owner=admin group=admin
  become: True

- name: find ssh keyfile name for use with git
  shell: grep IdentityFile ~/.ssh/config | awk '{print $2}'
  register: f_ssh_keyfile
  changed_when: False

  # configure communtity, one by one
- include: fastd-community.yml  mf_com={{mwu_mf_item.value}}
  with_dict: "{{community_params}}"
  loop_control:
    loop_var: mwu_mf_item
