---
- name: install ssl-cert packages
  package:
    name: ssl-cert
    state: present

- name: add users to ssl-cert group
  user:
    name: "{{ item }}"
    groups: ssl-cert
    append: yes
  loop: "{{ ssl_users }}"

- name: Add acme_server to known_hosts
  known_hosts:
    path: /etc/ssh/ssh_known_hosts
    name: "{{ acme_server }}.{{ http_domain_internal }}"
    key: "{{ lookup('file', acme_server + '.pub') }}"

- name: create cronjob to sync ssl certs
  template:
    src: ssl_certs.cron.j2
    dest: /etc/cron.daily/ssl_certs
    mode: 0755
    owner: root
    group: root
  notify: restart cron

- name: create certs directory
  file:
    path: "{{ ssl_directory }}/{{ ssl_cert_name }}"
    state: directory
    mode: 0550
    owner: admin
    group: ssl-cert

- name: create snakeoil cert
  shell: make-ssl-cert generate-default-snakeoil
  args:
    creates: /etc/ssl/certs/ssl-cert-snakeoil.pem

- name: copy snakeoil ssl key for first start
  copy:
    src: /etc/ssl/private/ssl-cert-snakeoil.key
    dest: "{{ ssl_key_path }}"
    remote_src: yes
    force: no
    owner: admin
    group: ssl-cert
    mode: 0440

- name: copy snakeoil ssl cert for first start
  copy:
    src: /etc/ssl/certs/ssl-cert-snakeoil.pem
    dest: "{{ item }}"
    remote_src: yes
    force: no
    owner: admin
    group: ssl-cert
    mode: 0440
  loop:
    - "{{ ssl_cert_path }}"
    - "{{ ssl_chain_path }}"

- name: try to sync ssl certs
  shell: /etc/cron.daily/ssl_certs
  ignore_errors: yes
