---
- name: add apt repository of neoraider
  apt_repository:
    repo: 'deb https://repo.universe-factory.net/debian/ sid main'
    state: present
    filename: 'neoraider'
  become: true
  notify: update apt cache

- name: add apt repository of freifunk-mwu
  apt_repository:
    repo: 'deb http://repo.freifunk-mwu.de/debian/ jessie main'
    state: present
    filename: 'ffmwu'
  become: true
  notify: update apt cache

- name: add apt-key of neoraider
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 16EF3F64CB201D9C
    state: present
  become: true
  notify: update apt cache

- name: add apt-key of freifunk-mwu package sigs
  apt_key:
    url: http://repo.freifunk-mwu.de/83A70084.gpg.key
    state: present
  become: true
  notify: update apt cache

- name: install needed packages for build-server
  apt:
    state: present
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 21600
  with_items:
    - apache2
    - apache2-utils
    - build-essential
    - ecdsautils
    - gawk
    - git
    - haveged
    - libncurses5-dev
    - libssl-dev
    - pkg-config
    - subversion
    - unzip
    - zlib1g-dev
  become: true
