---
- name: install git packages
  package:
    name: "{{ git_packages }}"
    state: present

- name: write git config
  template:
    src: "gitconfig.j2"
    dest: "/home/admin/.gitconfig"
  become: false

- name: ensure git directory is present
  file:
    path: /home/admin/clones
    state: directory
    mode: 0755
    owner: admin
    group: admin

- name: clone common git repositories
  git:
    repo: "{{ item.value.repo_url }}"
    dest: "{{ git_path }}/{{ item.key }}"
    version: "{{ item.value.version | default('HEAD') }}"
    force: "{{ item.value.force | default('no') }}"
    update: "{{ item.value.pull | default('yes') }}"
  loop: "{{ common_repos | dict2items }}"
  become: false

- name: clone additional git repositories
  git:
    repo: "{{ item.value.repo_url }}"
    dest: "{{ git_path }}/{{ item.key }}"
    version: "{{ item.value.version | default('HEAD') }}"
    force: "{{ item.value.force | default('no') }}"
    update: "{{ item.value.pull | default('yes') }}"
  loop: "{{ additional_repos | default(dict()) | dict2items }}"
  become: false
