---
- name: create routing tables
  lineinfile:
    path: /etc/iproute2/rt_tables
    regexp: '^{{ item.value }}'
    line: "{{ item.value }}{{ '\t' }}{{ item.key }}"
    state: present
  with_dict: "{{ routing_tables }}"
