---
- name: install fastd packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - fastd
    - git

- name: copy fastd status script
  copy:
    src: fastd-status
    dest: /usr/local/bin/fastd-status
    owner: root
    group: root
    mode: 0755
