---
- name: Manage Mail Server.
  hosts: mail

  roles:
  - powerdns.pdns_recursor
  - geerlingguy.mysql
  - mail-server

  vars:
    pdns_rec_install_repo: "{{ pdns_rec_powerdns_repo_41 }}"
    pdns_rec_flush_handlers: True
    pdns_rec_config:
      allow-from: "127.0.0.0/8, ::1/128"
      local-address: "127.0.0.1:53, [::1]:53"
    mysql_root_password: "{{ dbuser_root_password }}"
    mysql_databases:
      - name: "{{ db_modoboa }}"
        encoding: "utf8"
        collation: "utf8_general_ci"
    mysql_users:
      - name: "{{ dbuser_modoboa }}"
        host: "localhost"
        password: "{{ dbuser_modoboa_password }}"
        priv: "{{ db_modoboa }}.*:ALL"
      - name: "{{ dbuser_dovecot }}"
        host: "localhost"
        password: "{{ dbuser_dovecot_password }}"
        priv: "{{ db_modoboa }}.*:ALL"
      - name: "{{ dbuser_postfix }}"
        host: "localhost"
        password: "{{ dbuser_postfix_password }}"
        priv: "{{ db_modoboa }}.*:ALL"
    mysql_max_binlog_size: "100M"
    mysql_expire_logs_days: "10"
    mysql_bind_address: "127.0.0.1"
